### ISSUE TITLE
Records in actions log get duplicated after a while

### ISSUE THREAD

**Issue by dktapps** [blockparty-sh/craft.cash#10]
I noticed today in the "actions" pane of the wallet, after being AFK for some time my transactions started to show up multiple times in the window.

My real history:
![image](https://user-images.githubusercontent.com/14214667/48273787-ace8b200-e439-11e8-9761-89adab08a522.png)
My history after being AFK for a while: 
![image](https://user-images.githubusercontent.com/14214667/48273803-bf62eb80-e439-11e8-9852-fb44a50bc9bc.png)

Refreshing the webpage gets rid of the bug.

**Comment by blockparty-sh** [comment]
Looks like when it updates the list it isn't clearing the old values out. Thanks for report.
